# Generated by Django 5.2.17 on 2026-09-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.JSONField(default=dict)),
                ('services', models.JSONField(default=list)),
                ('statistics', models.JSONField(default=list)),
                ('testimonials', models.JSONField(default=list)),
                ('process_steps', models.JSONField(default=list)),
                ('seo', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenu du site',
                'verbose_name_plural': 'Contenu du site',
            },
        ),
    ]
