# Generated by Django 5.2.17 on 2026-09-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newscampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='frigo.o2switch.net', max_length=255)),
                ('port', models.PositiveIntegerField(default=465)),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('use_ssl', models.BooleanField(default=True)),
                ('use_tls', models.BooleanField(default=False)),
                ('from_email', models.EmailField(max_length=254)),
                ('timeout', models.PositiveIntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration SMTP',
                'verbose_name_plural': 'Configuration SMTP',
            },
        ),
    ]
