# Generated by Django 5.2.17 on 2026-09-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('entreprise', models.CharField(blank=True, max_length=150)),
                ('service_id', models.PositiveIntegerField(blank=True, null=True)),
                ('service', models.CharField(blank=True, max_length=200)),
                ('sujet', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('traite', 'Traite'), ('archive', 'Archive')], default='nouveau', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
